### ISSUE TITLE
Look into using travis ci for auto deploy

### ISSUE THREAD

**Issue by noahbass** [ACMatUC/acmatuc.github.io#4]
Look into using travis ci (free for open source) for auto deploying to master after a push to the develop branch

[Travis deploy docs](https://docs.travis-ci.com/user/deployment) - github pages is not an official integration, so a custom config is needed

[Example config](https://gist.github.com/domenic/ec8b0fc8ab45f39403dd)

**Comment by domfarolino** [comment]
Thinking about scrapping ng2 for this and doing custom instead. In mean time I'll check it out

**Comment by jondeibel** [comment]
Whatchu mean by custom @domfarolino?

**Comment by domfarolino** [comment]
No framework, minimal libraries. It's a thought of mine.

**Comment by noahbass** [comment]
Ahem.. Jekyll!

**Comment by domfarolino** [comment]
Regardless it's gonna wait until after the RevUC site lol. Right now it's doing ok.
