### ISSUE TITLE
RevUC organizer hall of fame

### ISSUE THREAD

**Issue by ArensKyle** [ACMatUC/acmatuc.github.io#43]
Noah would like to create a RevUC organizer hall of fame, and requested I file an issue for it to make sure it gets done.

**Comment by domfarolino** [comment]
More info would be great :)

**Comment by ArensKyle** [comment]
@noahbass Any more details to provide?

**Comment by noahbass** [comment]
A motion to create a RevUC organizer hall of fame is an idea that I may have jokingly suggested and has __not__ been put in front of the ACM@UC exec board.
I suppose this issue can stay open until the board votes on this.
😄

**Comment by jtsalisbury** [comment]
![image](https://user-images.githubusercontent.com/1310285/46508135-08f06300-c80a-11e8-9da2-284f3a3dbad5.png)
