### ISSUE TITLE
Need to add chairs to site 

### ISSUE THREAD

**Issue by linakaval** [ACMatUC/acmatuc.github.io#68]
@devagrawal09

**Comment by linakaval** [comment]
- Add chairs to site
- Update office hours

**Comment by devagrawal09** [comment]
Solved by [this](https://github.com/ACMatUC/acmatuc.github.io/commit/38a80f3c65dd943e2936cb843ea84a48ddb413c4) and [this](https://github.com/ACMatUC/acmatuc.github.io/commit/89bf63416b79c9bf94986b12f2dc3f320317b209).

**Comment by linakaval** [comment]
awesome, I appreciate it!
